### PR TITLE
Make drawing dpi independent

### LINKED ISSUE #42: Borders not set correctly
The edges of vi8 are clipped off making out difficult to guess words at the periphery. 
Screenshot_20201016-034836_Fennec

### LINKED ISSUE #134: Top and bottom cut off on Nokia 5.3
I'm a new user of 8vim.  On a stock Nokia 5.3 (Android 10), the top and bottom of the keyboard are cut off and letters/symbols are missing from view as a result.  See attached screenshot.
Screenshot_20201210-085845

### PR DESCRIPTION
**Pull request by npostavs**
Fixes #134 Fixes #42.
```
Replace uses of fixed pixel sizes with proportions related to canvas
text, or icon size.  Set text and icon sizes in sp (scale independent
pixel).  Scale thickness of lines (for circle and sector lines) by the
density.

Simplify computation of sector lines and letter positions by using
rotation Matrix.  The initial positions can then be easily computed
orthogonally, and then rotated into the diagonal without having to
deal with too much explicit trigonometry.
```

I tested at 320 & 420 dpi. The 320 shows the problem being fixed. The results at 420 dpi are not exactly the same, possibly some more tweaking is needed (although I'm not sure what the "real" sizes are supposed to be).

- Before
  - [320 dpi](https://user-images.githubusercontent.com/287742/118037922-76f35400-b33c-11eb-8e9a-14a9d1d6c049.png)
  - [420 dpi](https://user-images.githubusercontent.com/287742/118037924-778bea80-b33c-11eb-911b-b7d2c2baf59f.png)
- After
  - [320 dpi](https://user-images.githubusercontent.com/287742/118038017-94282280-b33c-11eb-9de2-79f794ef1e71.png)
  - [420 dpi](https://user-images.githubusercontent.com/287742/118038018-94282280-b33c-11eb-9275-f08e8146371b.png)

### CODE REVIEW

**Comment by flide** [comment]
Wow!!
Where can I read about this rotational matrix to understand it better?

**Comment by npostavs** [comment]
It's been a while since I've had to look at the math of this (and using the builtin class means you can kind of get away without it), but these seem like pretty good explanations:

- https://medium.com/hipster-color-science/computing-2d-affine-transformations-using-only-matrix-multiplication-2ccb31b52181
- https://people.cs.clemson.edu/~dhouse/courses/401/notes/affines-matrices.pdf
- https://www.algorithm-archive.org/contents/affine_transformations/affine_transformations.html (with animations)
- https://neutrium.net/mathematics/basics-of-affine-transformation/ (although the formulas shown here are for 3D transforms (x, y, z) which makes things a little more complicated. But the images all show the simpler 2D case)

**Comment by flide** [comment]
Icon placement is messed up with this commit.

WhatsApp Image 2021-05-13 at 22 52 39

**Comment by flide** [comment]
Also the letters are too spread out, looks good if the circle is at the center of the board, but leads to clipped characters if the center has been moved to any side significantly.

**Comment by npostavs** [comment]
hmm, it seems like the `keypadDimension` is leaving some space unused. Maybe I've misunderstood what it's supposed to represent? Also, what about when the y offset is maxed and there is simply no room for the icon? Should it be moved offscreen?

I added this code to `onDraw`
```
        foregroundPaint.setStyle(Paint.Style.STROKE);
        foregroundPaint.setColor(Color.RED);
        canvas.drawRect(0, 0, keypadDimension.getWidth(), keypadDimension.getHeight(), foregroundPaint);
        foregroundPaint.setColor(foregroundColor);
```
and I [get this](https://user-images.githubusercontent.com/287742/118166730-d7919800-b3f3-11eb-8b14-673845b23818.png).

**Comment by flide** [comment]
It's a difficult question to answer. I believe people start personalizing when they are comfortable with the product. 

So, if the user has maxed out a axis for center, most probable the user is experienced enough and don't even need the icon assistance, but then we can't assume that. 

I think the compromise would be to show the affected icons on the border of the board.

**Comment by npostavs** [comment]
I think I've compensated for the `keypadDimension` vs full View size asymmetry. I added some code to redraw after preferences are changed, so it's easier to test this too. The letters now take only as much spacing as there is available on the smallest direction. Though it's still possible to configure and [absurd results](https://user-images.githubusercontent.com/287742/118187334-c99c4100-b40c-11eb-8ee7-a4bf37162b61.png), I think most sane configs should be fine.

- [all the way to the right](https://user-images.githubusercontent.com/287742/118186773-1d5a5a80-b40c-11eb-86f0-2b3be6f696a3.png)
- [all the way to the left](https://user-images.githubusercontent.com/287742/118187486-fe0ffd00-b40c-11eb-979a-1c082dd3fdf4.png)
- [scrunching down near the bottom](https://user-images.githubusercontent.com/287742/118187404-e0db2e80-b40c-11eb-9470-7cd000f43aa1.png)
- [large circle](https://user-images.githubusercontent.com/287742/118187593-27c92400-b40d-11eb-924f-7d3415331ebc.png)

**Pull request merged**
