### PR TITLE
Add keypress sounds

### PR DESCRIPTION
**Pull request by npostavs**
I decided to try adding keypress sounds as a config option.

(#71 talked about sounds as well being able to turn off vibration)

### CODE REVIEW

**Comment by flide** [comment]
Can't hear any sound with the config turned on.

**Comment by flide** [comment]
Also, you don't need to force push your changes, just add a new commit to the branch and push the changes. Nothing to worry about the mistakes made, it helps understand the code and thought process better.

**Comment by npostavs** [comment]
Um, it works for me. Not sure what else to do about it.

> Also, you don't need to force push your changes, just add a new commit to the branch and push the changes

By the way, I haven't made any changes to this one, the force push was just due to rebasing. But I'll keep that in my mind for the future.

**Comment by flide** [comment]
Okay I finally figured out why it was not working for me, I had the "System sound -> Touch interactions" turned off hence no sound. After lot of discovery it works for me too now. sounds nice. Thanks.

**Pull request merged**
