### PR TITLE
Update it.yaml - letters disposition follows letter frequency

### PR DESCRIPTION
**Pull request by flauta**
As already done for iteration 11,  reorder the letters to put most frequent ones (in italian) near center.

### CODE REVIEW

**Review by MaethorNaur — APPROVED** [review]
LGTM

**Review by MaethorNaur — APPROVED** [review]

**Comment by flide** [comment]
This is a complete overhaul to the existing Italian board, I can't approve this unless a few of the Italian users support this PR.

**Comment by flauta** [comment]
> This is a complete overhaul to the existing Italian board, I can't approve this unless a few of the Italian users support this PR.

that's okay. Let's wait that some other italian user say what they think. 

I remember discussing this matter here some time ago, see [https://github.com/flide/8VIM/discussions/254](here)
(please note my layout follows the first proposed there)

At the moment I'm already using this map via the "Load from local" function.

**Comment by flide** [comment]
Calling all Italian users for comments!!

@flauta may be you can convince a few users to take a look at your changes before we merge them?

**Comment by Glitchy-Tozier** [comment]
Is this the layout?

**Comment by davidoskky** [comment]
@flide could you please provide an apk with this layout so that I can test it out?

Edit: No need, I tested it out. It seems good enough, but the letters with accents don't work.

**Comment by Glitchy-Tozier** [comment]
> ... but the letters with accents don't work.

For that, you might be able to use the stuff `@kjoetom` created (see the top 3 discussions in this repo).

**Comment by flauta** [comment]
> but the letters with accents don't work.

all accented letters work. Please note that the movement to shift to second layer - where accented letters are - must be completed to get the letter.

So the movement to get "ò" is B-C-B-C-L-B-C

**Comment by davidoskky** [comment]
Right, it does work.
I was expecting it to be C-L-B-L-C

**Comment by flauta** [comment]
> Is this the layout?

yes exactly this one. 

I have only repositioned the accented letters and symbols on the second and third layer, as requested by the new format

**Comment by flauta** [comment]
> Right, it does work. I was expecting it to be C-L-B-L-C

This is a consequence of the new 'multiple layers' system. 
First 4 movements shift to the second layer, other ones choose the desired letter.

**Comment by flide** [comment]
you can setup the accented letters in the first layer itself if you want.

**Comment by flauta** [comment]
> you can setup the accented letters in the first layer itself if you want.

yes I know. But the accented letters are less frequent than the others, and I started modifying the existing IT map, so they remain in the second layer. 

If my italian fellows don't approve it, accented letters can be moved anywhere else.

Please note that the actual disposition of letters in the existing IT map has the same accented letters in second layer AND some unfrequent letters near the center (eg. Y, B).

**Comment by flide** [comment]
I haven't seen any opposition to this layout, will wait another week before merging.

**Comment by flide** [comment]
Before I merge, please cast your vote on the poll #344

**Pull request merged**
