### PR TITLE
Kotlin code refactoring

### PR DESCRIPTION
**Pull request by degoncalves**

### CODE REVIEW

**Comment by flide** [comment]
Hey, were you able to get it running with Kotlin?

**Comment by degoncalves** [comment]
@flide Yes, I reverted your last commit. The selection keyboard is not working due to an NPE, but that has nothing to do with this PR.

**Comment by flide** [comment]
I think this is too old to pursue, can I close it @degoncalves ?

**Comment by degoncalves** [comment]
@flide Sure.

**Pull request closed without merging**
