### PR TITLE
Add optimized German layout (experimental)

### PR DESCRIPTION
**Pull request by adaschma**
@Glitchy-Tozier's experimental optimized layout.

### CODE REVIEW

**Comment by Glitchy-Tozier** [comment]
Thank you, looking forward to the next update.
With this, I might be able to come to new conclusions, which traits are important in a layout. :)

**Comment by flide** [comment]
this has been merged with minor file name change.

**Comment by Glitchy-Tozier** [comment]
How would a user be able to switch to a different language? I can't find the settings anywhere inside the app.

**Comment by flide** [comment]
Settings -> General -> 'select diacritics layout'

I now see the wordings could have been improved upon.

Regards,
Ravi

**Comment by Glitchy-Tozier** [comment]
I found that option, but where in memory are those layouts supposed to be?
On my device, I just get directed to a file-manager. The layout-files are nowhere to be found.

**Comment by Glitchy-Tozier** [comment]
Also, after downloading &unpacking this gihub-project just to get to the files, and after selecting `de_regular_german.xml` nothing changed. The old english layout stayed active.

**Comment by flide** [comment]
I see, the file exists but not much change to it. I guess @adamschmalhofer can answer this better.

If you want to use the layout you developed I will suggest you download the xml file uploaded by @adamschmalhofer in this PR on your device and use the option 'Select layout file from device' to activate it.

**Comment by Glitchy-Tozier** [comment]
>If you want to use the layout you developed I will suggest you download the xml file uploaded by @adamschmalhofer in this PR on your device and use the option 'Select layout file from device' to activate it.

That worked, thank you. That being said, I think a better mechanism needs to be implemented.

**Pull request closed without merging**
