### PR TITLE
Feature: Letter highlighting (as with the original 8pen) 

### PR DESCRIPTION
**Pull request by MaethorNaur**
Highlights the current letter on the pad by making it bold.
Also, update the pad to change to upper case the letter  when a complete turn is made

refs: #271

### CODE REVIEW

**Comment by flide** [comment]
@MaethorNaur Thanks.

**Comment by flide** [comment]
@MaethorNaur Thanks.

**Comment by flide** [comment]
mmm.... Can someone explain why I can't merge this?

**Comment by MaethorNaur** [comment]
Maybe you have to rerun the workflows?

**Comment by flide** [comment]
what workflows? I don't have any...

**Comment by MaethorNaur** [comment]
https://github.com/flide/8VIM/actions/workflows/android.yml

**Comment by flide** [comment]
okay okay, been away too long, don't remember setting up a android CI. Seems the last run failed, but logs are no longer available to see why that was. Can you request a CI run again on this PR?

**Comment by flide** [comment]
I am able to run it on my machine, so the build should not fail ... I don't see why the workflow failed.

**Comment by MaethorNaur** [comment]
I don't find the option. Otherwise, maybe you have to review the PR and accept the changes

**Review by flide — APPROVED** [review]

**Comment by flide** [comment]
https://user-images.githubusercontent.com/7330631/227946578-dcca6396-a474-4112-9a24-7cca9b4e12f0.mov

**Comment by MaethorNaur** [comment]
It seems that GitHub has some issues with PR ATM. https://www.githubstatus.com/

**Pull request merged**
