### PR TITLE
Material design

### PR DESCRIPTION
**Pull request by MichalLebeda**
Updated settings & keyboard to material design. It is not 100% but still IMO looks good enough. Keyboard is also themeable.

### CODE REVIEW

**Comment by flide** [comment]
This is brilliant!!
Can you resolve the lint issues please before the merge?

**Comment by MichalLebeda** [comment]
@flide done, also fixed some lint issue introduced even before. You can probably squash it as my commit history is not the best (the begining of the process was a bit of a trial and error). There are some newly introduced issues.
1. This branch uses an other config file so settings are not moved (would be incompatible terms of colors and circle scale anyway).
2. We should probably define constants for scale range, sector buttons alpha etc somewhere, but IDK where.
3.  I have removed line draw from trail and kept only dots as a workaround for that ugly glitch, but this caused end of the line look a bit strange (dotted)
4. More params of the keyboard are loaded when keyboards starts and I don't know how to apply changes on the fly when pref change occurs.

**Comment by flide** [comment]
There are couple of issues with the current changes : 

1. Selecting the 'emoji keyboard' from the settings no longer actually selects the keyboard to open when clicking the emoji button.
2. Sidebar is not changing position even on a restart. (And, really sorry, I still have no way for the settings to take effect without a keyboard switch and back)


By the way... I have no idea how you did it, but it looks awesome...

**Comment by MichalLebeda** [comment]
Thanks, I overlooked those things, will fix them

**Comment by flide** [comment]
Trail also feels so much more smoother then before... I need to dive into your changes soon.

**Comment by flide** [comment]
Everything seems to be working now.
Thanks for your effort !!

**Comment by MichalLebeda** [comment]
No problem, will make more PRs as soon as I have time

**Pull request merged**
