### PR TITLE
feat: add quicker movements for extra layers

### PR DESCRIPTION
**Pull request by MaethorNaur**
Add missing diacritics for spanish layout

refs: #321

### CODE REVIEW

**Comment by flide** [comment]
What are these quick movements ?

**Comment by MaethorNaur** [comment]
@flide cf: #321

**Comment by flide** [comment]
@MaethorNaur are you stating with this PR that you fixed **_ALL_** the layouts?

**Comment by flide** [comment]
@MaethorNaur still needs to resolve some conflicts it seems.

**Pull request merged**
