### PR TITLE
feat: haptic rotation feedback

### PR DESCRIPTION
**Pull request by mrshmllow**
This option adds feedback to rotation, helping muscle memory and reducing dependence on visual feedback.
It helps me think, oh, "c" is 2 and I simply count 2 "ticks" of the imaginary dial.
I thought of this idea for myself and added it, maybe its useful for other people

### CODE REVIEW

**Comment by mrshmllow** [comment]
I have been practicing and its significantly increased my WPM

**Comment by guancio** [comment]
I would love to have touch feedback, but I hate phone haptic vibrations. I'm really thinking of buying a new screen protector and engrave the keyboard diagonals :)

**Comment by MaethorNaur** [comment]
> I would love to have touch feedback, but I hate phone haptic vibrations. I'm really thinking of buying a new screen protector and engrave the keyboard diagonals :)

Sorry for the delay.
The current option for the haptic is relatively low (in my device). Maybe we could add preferences to adjust the duration/strength?

Also, I've separated the vibration code from the listener (separation of concern principle)

**Comment by mrshmllow** [comment]
a change i wrote in 2 minutes total has been turned into 80 lines i love oop

**Comment by MaethorNaur** [comment]
Feature add in #445

**Pull request closed without merging**
