### PR TITLE
feat: :sparkles: Adaptative circle centre and new haptics options

### PR DESCRIPTION
**Pull request by MaethorNaur**
Offset the centre of the circle depending on the initial finger position.

- Added settings for more haptic options
- Fix/Improve haptics feedback
- Add haptics feedback when crossing a sector

refs: #304, #341

### CODE REVIEW

**Comment by ManDay** [comment]
Looks great. The only thing that I would still change is that the circle shrinks *immediately* as soon as you touch it. Do you see any reason why this could become a problem?

**Comment by MaethorNaur** [comment]
Indeed, I could see how to add a transition

**Comment by ManDay** [comment]
There is something not quite working, though. It appears almost as if the crossing through sectors is detected based upon the original circle, not the re-centered shadowed one. I attach a video which shows the problem. Particularly the two inputs `l` and `o` were certainly wrong.

https://github.com/8VIM/8VIM/assets/1059827/8285c6f6-4d2d-4789-a03a-733f9f0008d2

**Comment by MaethorNaur** [comment]
@ManDay Should be fixed

**Comment by ManDay** [comment]
I think it's technically flawless now. As a matter o0f taste, I would NOT resize the circle when the touch started in one of the sectors, though.

**Pull request merged**
