### PR TITLE
Language spanish

### PR DESCRIPTION
**Pull request by adaschma**
Here is the English 8pen layout with the Spanish diacritics.

### CODE REVIEW

**Comment by Glitchy-Tozier** [comment]
@adamschmalhofer Do you plan on tackling German, eventually?

**Comment by flide** [comment]
A basic board english board with German diatrics as already in.

Although, I think you would rather enjoy a German board completely defined
from scratch.

**Comment by Glitchy-Tozier** [comment]
Yes, that would be very enjoyable.

Apparently though, a German layout [already exists](https://github.com/adamschmalhofer/8VIM/releases/tag/devel-1), thanks to `@adamschmalhofer`. (It can be found [here](https://github.com/flide/8VIM/issues/144#issuecomment-750441819)).

Looking forward to you releasing the next version of 8Vim into the Play-Store.

**Comment by flide** [comment]
The added German layout is courtesy of  @adamschmalhofer.

**Comment by Glitchy-Tozier** [comment]
Yeah, I kind of overlooked his German PR.

**Comment by flide** [comment]
It's fairly easy to add a new layout now, if you want to try out a custom
layout just add a new file.

**Comment by Glitchy-Tozier** [comment]
@adamschmalhofer I could calculate some really good layouts for quite a few languages for you to add.

Would you be interested or are you focusing on the 8pen layouts?

**Comment by adaschma** [comment]
@Glitchy-Tozier 

I think both have there justifications. Will you include the diacritics
into the calculations? While I plan to add the optimized German, I think
we should wait at least an iteration with adding more optimized layouts.
This will be our first own layout and experience tells us that once we
actually use it, we will likely want changes. I know I'm not telling you
anything new as you emphasized yourself, that we needs to be
communicated clearly that it is experimental. I would prefer to wait
until the optimizations have stabilized before doing all the work of
releasing it to the wild. Also I'm excited of the lessons you have learned 
from the KOY/Neo communities :-).

I'll use this opportunity to say what bothers me most on the 8pen layout
(after using it for a few months): Of all things it is entering the "."
and ",". While it seems to make sense to let them be slower to enter as
there is a pause this pause is shorter then the sound of a letter and it
really feels slow to me.

**Pull request merged**
