### PR TITLE
Use github action to auto release

### PR DESCRIPTION
**Pull request by MaethorNaur**

### CODE REVIEW

**Comment by flide** [comment]
@MaethorNaur Is this ready?

**Comment by MaethorNaur** [comment]
Not yet. it would be better to discuss about that one

**Comment by bonswouar** [comment]
Hi, because of the [shortcuts missing for diacriptics](https://github.com/8VIM/8VIM/issues/321) I _(and I guess, probably 99% of all non-english speaking users)_ haven't been able to use 8vim for some months now. Any plan to use this feature to release a new usable version?

(I didn't want to use the debug build, I preferred to wait for the official release)

**Comment by flide** [comment]
we will make  release asap

**Pull request merged**
