### PR TITLE
feature: Update the keyboard to support multiple layers

### PR DESCRIPTION
**Pull request by MaethorNaur**
Now 8VIM can support up to 6 layers of different characters.

But in order to do that I had to rethink the file structure.

I moved from `XML` to `YAML`.

It's easier to parse (it directly maps to an object) and it's easier to read.

In order to simplify and make it easier to create/update layouts, I divided them by layers/sectors. `characterSets` are no more needed for the creation of the keyboard (inferred from the layer).
Same for the `movementSequence`: the sequence is also inferred from the `YAML`. (But it can be overridden in the property set in the YAML).

Here is a small sample:

```yaml
hidden: # the hidden layer is never rendered
  NO_SECTOR: 
    - actionType: INPUT_KEY
      movementSequence:
        - TOP
        - INSIDE_CIRCLE
        - NO_TOUCH
      keyCode: HIDE_KEYBOARD
visible:
  - RIGHT_BOTTOM:
      - actionType: INPUT_TEXT
        lowerCase: n
        upperCase: N
      - actionType: INPUT_TEXT
        lowerCase: m
        upperCase: M
      - actionType: INPUT_TEXT
        lowerCase: f
        upperCase: F
      - actionType: INPUT_TEXT
        lowerCase: "!"
  - RIGHT_BOTTOM:
      - null 
      - actionType: INPUT_TEXT
        lowerCase: o
        upperCase: O    
```

It will create a keyboard with `nmf!` at the bottom of the right sector, with a second layer ` o  `
All movement sequences (lower and upper cases) are computed from that.

-----

Quick doc:

```yaml
hidden: Quadrant_keyboardActions # hidden layer
visible: [Quadrant_keyboardActions] # visible layers
```

`Quadrant_keyboardActions`: is a map.
The key is one of the available quadrants.
The value is a list of `keyboardAction`.
On visible layers/quadrants that list cannot exceed 4 items (other items will be discarded).
Each item represents a character on the quadrant (from the centre).
To skip an entry the value must be `null` or an empty object `{}`.
The first map of the visible layer will be the default layer rendered.

`Quadrant`:

- `RIGHT_BOTTOM`
- `BOTTOM_RIGHT`
- `BOTTOM_LEFT`
-  `LEFT_BOTTOM`
-  `LEFT_TOP`
-  `TOP_LEFT`
- `TOP_RIGHT`
- `RIGHT_TOP`
- `NO_SECTOR`. Special quadrant in which the characters are never rendered on the keyboard but the action works for the layer.

`keyboardAction`:

```yaml
actionType: KeyboardActionType # `INPUT_TEXT` or `INPUT_KEY`
lowerCase: a # character to render for `INPUT_TEXT`
upperCase: A # character to render for `INPUT_TEXT` when the upper case is required.
movementSequence: [FingerPosition] # Optional, if this property is set and non-empty the inferred movement sequence will be overridden
keyCode: SHIFT_TOGGLE # key code event only when `actionType` is `INPUT_KEY`
flags: 0 # Optional flags
```

`FingerPosition`:

- `NO_TOUCH`
- `INSIDE_CIRCLE`
- `TOP`
- `LEFT`
- `BOTTOM`
- `RIGHT`
- `LONG_PRESS`
- `LONG_PRESS_END`

BREAKING CHANGE: The new format is not backwards compatible

refs: flide/8VIM#292

### CODE REVIEW

**Comment by MaethorNaur** [comment]
Open to suggestions 😄

**Comment by MaxGyver83** [comment]
I just stumbled over this pull request and I like this idea.

Some days ago I started playing around with 8VIM. I noticed that the default German layout is far from optimal. (P.e. "y" is on the inner ring and it's one of the least used letters, even behind "ö" and "ß".) Then I found [Glitchy-Tozier/8vim_keyboard_layout_calculator](https://github.com/Glitchy-Tozier/8vim_keyboard_layout_calculator) and generated a better layout. But I had difficulties updating the existing xml file without errors.

Yesterday, I started writing a script that takes a very simple yaml file as input and creates a valid xml configuration from it.
This yaml file looks like this:

```yaml
---
clockwise:
  top:    [s, f, p, ['@', '@gmail.com']]
  right:  [a, g, b, ['!', '!']]
  bottom: [e, d, k, j]
  left:   [t, l, y, [., '-']]

counterclockwise:
  top:    [n, u, v, ["'", '"']]
  right:  [r, m, x, ['?', '*']]
  bottom: [i, h, z, q]
  left:   [o, c, w, [",", _]]
...
```

The script is not yet complete and the yaml file doesn't handle diacritics yet. (I actually want to create `ä`, `ö`, `ü` and `ß` automatically, following the same pattern that is used already in the default German layout.)

I'm wondering if xml is mandatory at all!? Maybe you could introduce an even simpler (and less verbose) yaml instead of your new xml format (which is already a great improvement)?

**Comment by MaethorNaur** [comment]
I don't know if XML is mandatory, but the XML library is native.
I would love to move from `XML` to `YAML`.
I'm going to fork this branch and use `YAML` instead of `XML`

**Comment by MaethorNaur** [comment]
The YAML version: MaethorNaur/8VIM#2

**Comment by MaethorNaur** [comment]
YAML files are easier to edit

**Comment by MaethorNaur** [comment]
Added the PR for the Ukrainian language: Add Ukrainian language: #302

**Comment by MaxGyver83** [comment]
Very cool!

Some thoughts:

1. The `actionType` is almost always `INPUT_TEXT` (in 1302 of 1325 cases, about 98 %). We could make this the default and only set the `actionType` when it's **not** `INPUT_TEXT`.
2. When `lowerCase` is a lower case letter, (almost?) always `upperCase` is the upper case version of this letter. Not a surprise :-) We can assume that this is what most people want. So we could make it a rule that if `lowerCase` is a letter and `upperCase` is not set, then `upperCase` is the upper case version of that letter.

This would simplify the layout config files even more. Almost as simple as my version above ;-)

**Comment by MaethorNaur** [comment]
Good idea. I've made the changes

**Comment by MaxGyver83** [comment]
I like it! But I'm just a user, not the project maintainer. So I'm curious what @flide thinks about it!

**Comment by MaethorNaur** [comment]
I'm a user too ^^, but I hope it will please everyone 😄

**Comment by flide** [comment]
I like these changes but i think these need to be documented somewhere for anyone writing a new layout file. Can a wiki page be added which teaches how to write a new layout file?

**Comment by MaethorNaur** [comment]
Will do. As long we agree on the final format :)

**Comment by MaethorNaur** [comment]
@flide I created the documentation: https://github.com/MaethorNaur/8VIM/blob/new-file-layout/Adding-new-language.md.

For some reason, I cannot create a PR for the WIKI. If you are happy with that you can add that file into the wiki repository

**Comment by flide** [comment]
This is brilliant, I just need to understand what is the distinction between 'hidden' layer and 'visible' layer. 
Also, I guess, there can be multiple 'visible' layers?
Also also, what is the mechanism that switches between different visible layers?
And, can you point to a file which contains all the various elements that it can contain?
@MaethorNaur

**Comment by flide** [comment]
I was analysing the "de_regular_germal.yaml".
- I don't understand the difference between the label '- RIGHT_BOTTOM' and 'RIGHT_BOTTOM'
- There is no clear differentiation between the different layers, atleast I am not able to understand it in one go.

can you help me understand please.

**Comment by MaethorNaur** [comment]
> I was analysing the "de_regular_germal.yaml".
> 
> * I don't understand the difference between the label '- RIGHT_BOTTOM' and 'RIGHT_BOTTOM'
> * There is no clear differentiation between the different layers, atleast I am not able to understand it in one go.
> 
> can you help me understand please.


- for `RIGHT_BOTTOM` and `BOTTOM_RIGHT` as described in the doc, the first part is the sector and the second part is the position in the sector. `LEFT`/`RIGHT` have `TOP`/`BOTTOM` position and `TOP`/`BOTTOM` have `LEFT`/`RIGHT`.
Maybe we can split into sector/part.

for example:

```yaml
visible:
  - RIGHT:
       TOP:
          - lowerCase: a
        BOTTOM:
          - lowerCase: n
 ```

About `hidden` and `visible`.

The hidden layer is primarily an internal layer, but the purpose of it is to handle movements and do an action/add a character but there is no need to be rendered on the keyboard. I wrote that in the doc more for information.
When adding a language there is no need for it.

Also, I remove the `NO_SECTOR`. it was only needed for: `zero_turn_no_actions.yaml`, but I removed it as it wasn't really useful.
So `hidden` directly takes a list of actions.

If you want to make a clear distinction between the layers we could (yaml can makes hard to read list):

```yaml
layers:
  hidden:
    ...
  default:
    ..
  extra_layers:
    first:
     ...
   second:
     ...
   third:
     ...
   fourth:
     ...
  fifth:
   ..
```

What do you think?

@flide

**Comment by MaethorNaur** [comment]
@flide

Update documentation to explain how to use the layers: https://github.com/MaethorNaur/8VIM/blob/new-file-layout/Usability-Guide.md

**Comment by MaethorNaur** [comment]
@flide

I added the support of the cut action on the selected text.

Updated the usability documentation:

- Added visual explanation for the selection/cut/copy/paste.
- Added documentation for the "embedded" emojis with a visual explanation.

**Comment by mentalisttraceur** [comment]
Hopefully a quick question: will it be possible with these changes to specify keys like Shift, Ctrl, Alt/Opt/Meta, Win/Cmd/Super, Esc, Enter, Backspace, and so forth?

If not, is the design at least conceptually/architecturally compatible with adding it later?

(I don't want separate clickable areas like the current stock 8vim layout does, I want everything accessible within the same smooth continuous finger swirl, including enabling/locking/disabling each modifier. My intent is to eventually contribute the ability to do that if it's not already possible, so I'm just hoping/asking that this doesn't take us further from that goal.)

**Comment by MaethorNaur** [comment]
I'm not sure about your question. Do you mean for instance if a full round (which brings the upper case letters) shows the shift key icon?

**Comment by mentalisttraceur** [comment]
I mean that I'd love to write mappings like this:

```yaml
  - RIGHT_BOTTOM:
      - actionType: INPUT_TEXT
        lowerCase: n
        upperCase: N
      - actionType: INPUT_TEXT
        lowerCase: m
        upperCase: M
      - actionType: INPUT_TEXT
        lowerCase: f
        upperCase: F
      - actionType: MODIFIER
        lowerCase: Shift
  
  - RIGHT_TOP:
      - actionType: INPUT_TEXT
        lowerCase: a
        upperCase: A
      - actionType: INPUT_TEXT
        lowerCase: r
        upperCase: R
      - actionType: INPUT_TEXT
        lowerCase: x
        upperCase: X
      - actionType: MODIFIER
        lowerCase: Ctrl
 ```
 
So the motion that in the default layout creates `!` would instead work like tapping the top quadrant does now:

1. do it once and Shift is in effect for just the next input - the standard terminology for this is that Shift is "latched";
2. do it twice in a row and Shift is in effect until it's toggled again - standard terminology: Shift is "locked";
3. do it again after it's already locked and Shift stops being in effect.
  
If 8vim isn't already able to generate the other modifier keys (Ctrl, Alt/Opt/Meta, Win/Cmd/Super, etc), I fully intend to eventually add a PR to do that - there's even many open source "programmer's" Android keyboards that already do this which we can look at for a quick reference for how it's done.

So the question is: does what you're doing in this PR make it possible/easier? (And the request is: just please don't use a design which would make it impossible/harder.)

**Comment by MaethorNaur** [comment]
So if you do a full rotation, the shift is "latched" (The icon is not updated yet, but it can be fixed).
I can do a double rotation to "lock" the shift.

Other modifier keys are not supported yey, but could be on an other PR

**Comment by mentalisttraceur** [comment]
Okay, assuming we mutually understood each other correctly, that makes me really happy to hear, and even if we didn't, that still makes me pretty happy to hear. Thank you for the great work!

**Comment by MaethorNaur** [comment]
@mentalisttraceur
Updated the keyboard. every full rotation will:

- Shift
- Shift lock
- lower case

**Comment by AsafMahlev** [comment]
So the original seems to be abandoned and this shapes to be the defacto fork

I just wanted to suggest, currently all motions are described in full 
So when the actionmap is loaded, it contains every possible combination of actions for every layer, which is why I assume the limit is there.

I think a more efficient way would be to add relative actions - CLOCK and ANTICLOCK, NEXT and PREV, and have the system calculate them at runtime. 

Clock and ANTICLOCK denote motion based on the current quadrent - Right, Down is the same of Right, Clock for example

Now once you have a movement like this, you have a direction, NEXT repeats the movement, PREV reverses it.

Now any letter is simply defined by a start quadrent, Clock or anticlock, and an amount of nexts.

You can just count the nexts to see what letter it is.

Layer up could be simply be defined as PREV. (Though I did make a suggestion that it should at least be configurable to make it go back to the previous letter instead, in case you make a mistake)

Layer down is PREV, NEXT etc

Now layers can be a part of the system and not be generated when loading the yamls

I can help implement this if this is the direction you want to go in.

Other suggestions in general:
- switching languages (wee my issue on this repo)
- when finishing not on the circle, instead of doing nothing it just inserts the last letter without a space. At least have it be configurable.
- Showing a preview of what is going to be printed, which is helpful for your added gestures
- other suggestions on the repo, such as adding numbers and symbols to the 8vim keyboard, dynamic start position, custom symbols or expansions when holding on a letter, etc

I think until the owner of this repo is back you should make yours the defacto one, and let me know if there's a suggestion you want me to contribute on

Thanks

**Comment by AsafMah** [comment]
More Ideas:

- Double tapping
* Double tap the circle for a dot
* Double tap and move to an arrow to select in that direction
* Double tap right for "select all"
* etc

- Modifiers
There are already ctrl and shift, have them act like a pc.
* When shift is held letter are capitals, when left goes back
* When control is held movement/selection/deletion is by word and not by lettter

- Using the lines
* Tapping on letters on the line to write them (escape hatch?)
* Move along the line forwards/backwards for an action/step
* holding letters in the line for macros/etc

I really feel like the design opprotunities for this keyboard are limitless

**Comment by MaethorNaur** [comment]
@AsafMah

> More Ideas:
> 
> * Double tapping
> 
> * Double tap the circle for a dot
> * Double tap and move to an arrow to select in that direction
> * Double tap right for "select all"
> * etc
> 
> * Modifiers
>   There are already ctrl and shift, have them act like a pc.
> 
> * When shift is held letter are capitals, when left goes back
> * When control is held movement/selection/deletion is by word and not by lettter
> 
> * Using the lines
> 
> * Tapping on letters on the line to write them (escape hatch?)
> * Move along the line forwards/backwards for an action/step
> * holding letters in the line for macros/etc
> 
> I really feel like the design opprotunities for this keyboard are limitless

Those are good ideas, however, I might not integrate them into that PR, which is already massive. Could you open an issue with those ideas?

**Comment by MaethorNaur** [comment]
@AsafMahlev 

> So the original seems to be abandoned and this shapes to be the defacto fork
> 
> I just wanted to suggest, currently all motions are described in full So when the actionmap is loaded, it contains every possible combination of actions for every layer, which is why I assume the limit is there.
> 
> I think a more efficient way would be to add relative actions - CLOCK and ANTICLOCK, NEXT and PREV, and have the system calculate them at runtime.
> 
> Clock and ANTICLOCK denote motion based on the current quadrent - Right, Down is the same of Right, Clock for example
> 
> Now once you have a movement like this, you have a direction, NEXT repeats the movement, PREV reverses it.
> 
> Now any letter is simply defined by a start quadrent, Clock or anticlock, and an amount of nexts.
> 
> You can just count the nexts to see what letter it is.
> 
> Layer up could be simply be defined as PREV. (Though I did make a suggestion that it should at least be configurable to make it go back to the previous letter instead, in case you make a mistake)
> 
> Layer down is PREV, NEXT etc
> 
> Now layers can be a part of the system and not be generated when loading the yamls
> 
> I can help implement this if this is the direction you want to go in.

It's something we could do in the future, but I prefer not to make these changes in that PR.
This PR is already big and delaying it might impact other PR.

> Other suggestions in general:
> 
> * switching languages (wee my issue on this repo)
> * when finishing not on the circle, instead of doing nothing it just inserts the last letter without a space. At least have it be configurable.
> * Showing a preview of what is going to be printed, which is helpful for your added gestures
> * other suggestions on the repo, such as adding numbers and symbols to the 8vim keyboard, dynamic start position, custom symbols or expansions when holding on a letter, etc
> 
> I think until the owner of this repo is back you should make yours the defacto one, and let me know if there's a suggestion you want me to contribute on
> 
> Thanks

* Not sure about what you mean by switching languages?
* That would be nice, feel free to create an issue/PR for that
* Not sure about that one (it's true for special movements, like emojis, special characters are not shown :( )
* Numbers/symbols can be added easily (as long we agree on the patterns). Same feel free for an issue/PR

**Comment by flide** [comment]
@MaethorNaur This PR is gone out of hand, I am not able to review the code. Would you be willing to have a online meeting with me to explain and discuss the PR? Any time on Saturday or Sunday according to Indian Standard Time (IST), I think we should be able to clear everything up in 30 mins or so.

**Comment by MaethorNaur** [comment]
Yes, absolutly

**Comment by flide** [comment]
@MaethorNaur I have verified your changes, and I think this PR is ready for merge. Is there anything pending or more you want to add to this PR before merging ?

**Comment by flide** [comment]
@AsafMahlev @AsafMah You seem to have interesting ideas for the keyboard, please open up discussions on yours ideas, one at a time, and let the community weigh in.

**Comment by MaethorNaur** [comment]
@flide It was working.
Let me double check though.
Also, let me update the wiki first

**Comment by MaethorNaur** [comment]
@flide 

I just thought, maybe we could display which layer is activated.
To be in the layer selector mode is:
- bottom
- circle

then, select the layer, and go back to the bottom (2nd layer). If you rotate clockwise you change the layer. (2nd, 3rd, ...) the last layer is when you come back to the bottom.
To validate your layer you have to go to the circle. Then you can choose the character you want as usual.
But there is a caveat: once a character is selected from a layer, the keyboard switches back to the default layer.

Would we want to keep the layer (maybe adding a movement to come back to the default one?)

**Comment by flide** [comment]
I think switching to the default layer is the right thing to do. The characters in these layer are inherently lesser used, and highly unlikely that two of them are in sequence.

**Pull request merged**
