### PR TITLE
Language German

### PR DESCRIPTION
**Pull request by adaschma**
Here is the English 8pen layout with the German diacritics. Sadly, I couldn't test it, as the "Choose the diacritics" menu is empty (both with and with out this new file). I tried deinstalling and reinstalling 8vim, but that didn't fix it sadly.

### CODE REVIEW

**Comment by flide** [comment]
works for me just fine.

**Comment by lxne** [comment]
diacritics menu is empty for me, too.
Any idea what I could do about it?

Fairphone 4. Android 11
8Vim iteration-8

**Comment by adaschma** [comment]
> diacritics menu is empty for me, too. Any idea what I could do about it?
> 
> Fairphone 4. Android 11 8Vim iteration-8

for me the menu was empty when I compiled it myself. On the other hand getting it from f-droid.org the menu was filled. Where did you get 8vim from?

**Comment by ThomasAH** [comment]
For me the diacritics menu was empty in Iteration-8 from F-Droid and Google Play (Pixel 4a with Android 11, current LineageOS 18.1).
(Fresh installation of 8Vim in both cases)

**Comment by flide** [comment]
can someone post a bug report for this with screenshots.

**Comment by lxne** [comment]
> > diacritics menu is empty for me, too. Any idea what I could do about it?
> > Fairphone 4. Android 11 8Vim iteration-8
> 
> for me the menu was empty when I compiled it myself. On the other hand getting it from f-droid.org the menu was filled. Where did you get 8vim from?

I got it from the f-droid app.

**Comment by adaschma** [comment]
> > diacritics menu is empty for me, too. Any idea what I could do about it?
> > Fairphone 4. Android 11 8Vim iteration-8
> 
> for me the menu was empty when I compiled it myself. On the other hand getting it from f-droid.org the menu was filled. Where did you get 8vim from?

I made a mistake. It turns out I failed to switch versions and was still using a self compiled version that filled the menu differently. From f-droid it still has an empty menu.

**Pull request merged**
