### PR TITLE
WIP: Theming Support

### PR DESCRIPTION
**Pull request by LunarEclipse363**
An attempt to solve #41.

### CODE REVIEW

**Comment by flide** [comment]
I have not been able to find time to look at the code yet, I will go through it soon and update you.

**Comment by flide** [comment]
I looked through the code and realized that i need to clean the lint errors before making these kind of changes as many errors are because of the way i use paints and colours. also, i am currently allocating memory for objecs within the ondraw function causing instability. 

I am working to fix those issues.

**Comment by LunarEclipse363** [comment]
I see, in that case feel free to tell me when you think I could give this another go 🙂
I'll probably take a look at the official android dev courses in the meantime to get a better understanding of what I'm actually doing 😁

**Comment by flide** [comment]
@Mckol , take a look at the branch https://github.com/flide/8VIM/tree/bug/keyboard_colour_fix
I was able to fix-up basic color management.

Still far off from the true color management using styles, but it's some progress and no-crashes :smile:

**Comment by flide** [comment]
@Mckol , I have merged everything to master. You can make a pull and continue experimenting.

**Comment by flide** [comment]
Closing this PR as stale

**Pull request closed without merging**
