### PR TITLE
language selection including hebrew and diacritics

### PR DESCRIPTION
**Pull request by adaschma**
As promised here are the diacritics for the "single layered languages" in 8vim's xml file format.

### CODE REVIEW

**Comment by adaschma** [comment]
I now added a way for the human to select which layout to use. This includes changing the letters displayed on the "X" (currently used for the Hebrew layout). So this would close #20 #159 and #144.

**Comment by Glitchy-Tozier** [comment]
Nice job, that's an exciting update! Will check it out when it arrives in the play-store.

**Comment by flide** [comment]
This is brilliant, but couple of improvements are required.
1. The set of characters for selected language/layout should be part of the xml itself and should not require changes to the "strings.xml".
2. There should be a automatic search for available language/layout files in the raw folder to show up as available keyboard layouts. This means there needs to be a set format to name the language/layout files.


Also... this one is a bit of a selfish request... please don't change the input gestures for the "en_eight_pen_esperanto.xml".... kinda pretty attached to it... it's in my practice for over 5 years now...

**Comment by flide** [comment]
Also, it might be better to have a PR for each layout, so that folks who are actually interested in a particular layout might be able to provide useful comments/suggestions/changes. This is too much change for a single commit.

**Comment by adaschma** [comment]
I agree that 1+2 are nice to have. To 3: wasn't aware that you type Esperanto. Making the diacritics a bit inconsistent to have backwards compatibility is reasonable. 

That being said: I hope somebody picks it up, as I most likely won't. In this project I noticed that programming in Java is rather too close to my dayjob with C# to feel relaxing enough. So I've decided to work on other projects instead. Sorry, to give you that bad news.

**Comment by flide** [comment]
No issues, you have already contributed enough to go over the initial hump.

Thanks for your efforts.

**Comment by flide** [comment]
This PR is not going to be merged any longer, but I am keeping it open if anyone wants to reference the layout data which @adamschmalhofer has painstakingly compiled.

**Comment by adaschma** [comment]
Closing as they have now been ported to the new format.

**Pull request closed without merging**
